### ISSUE TITLE
Remove cassandra dep and read from postgres and code points

### ISSUE THREAD

**Issue by camallen** [zooniverse/aggregation#124]
@ggdhines can you share some code links on where to switch the db reader dep in the codebase?

**Comment by ggdhines-zz** [comment]
In aggregation_api.py, there is a call to the function **cassandra_annotations** - the function is at https://github.com/zooniverse/aggregation/blob/b31daa9bcbf3711b009bf125c825041c8db3f429/engine/aggregation_api.py#L381 - replace the code there with a call to postgres. **cassandra_annotations** is called at https://github.com/zooniverse/aggregation/blob/b31daa9bcbf3711b009bf125c825041c8db3f429/engine/aggregation_api.py#L1711 The actual call to query the cassandra db is at https://github.com/zooniverse/aggregation/blob/b31daa9bcbf3711b009bf125c825041c8db3f429/engine/aggregation_api.py#L402 and it is a simple select statement - there is stuff around that line to have the query be done concurrently which can be ignored if you're using postgres. 
Annotations are copied from postgres to cassandra using **migrate** https://github.com/zooniverse/aggregation/blob/b31daa9bcbf3711b009bf125c825041c8db3f429/engine/aggregation_api.py#L1164 which you can basically just cut out. **migrate** also returns a list of subjects to aggregate over. You could do this with a simple query in postgres to get all the annotations since you last ran the aggregation and get those corresponding subjects. (I should try to do this anyways before I leave since that would really simplify things.)

**Comment by camallen** [comment]
thanks looks good.
