### ISSUE TITLE
Errors loading annotation JSON

### ISSUE THREAD

**Issue by edpaget** [zooniverse/aggregation#14]
It looks like the annotations hashes are being loaded into Cassandra with an extra set of quotation marks around them as in, so calling `json.loads` parses the JSON into a string and calling `json.loads` a second time actually parses it into an annotation object.

**Comment by ggdhines-zz** [comment]
In aggregation_api.py, the commands that migrate the annotations from postgres to cassandra are:
params = (project_id, user_id, workflow_id,created_at, json.dumps(annotations), updated_at, user_group_id, user_ip,  completed, gold_standard,  subject_ids[0], workflow_version,json.dumps(metadata))
            statements_and_params.append((insert_statement, params))

Since Cassandra doesn't support json - I've just converted the annotations into a string with json.dumps. No idea why that should result in an extra set of quotation marks.

**Comment by edpaget** [comment]
I was wondering if it was because they were being read as strings from Postgres by the Python Postgres driver.

**Comment by ggdhines-zz** [comment]
I would have thought that the annotations would be kept as a dictionary (since that is what they are stored as) but the updated code should help with that check

**Comment by edpaget** [comment]
Thanks. I'll give it another try soon.

**Comment by ggdhines-zz** [comment]
According to @edpaget , this seems to be working now
